name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Frontend Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image (Frontend)
      run: |
        docker build \
          --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} \
          -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

    - name: SSH into EC2 and Deploy Frontend
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.AWS_EC2_IP }} << 'EOF'
          # Create shared network if not exists
          docker network create app-network || true
          
          # Deploy frontend
          docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:latest
          docker stop frontend || true
          docker rm frontend || true
          docker run -d \
            --name frontend \
            --network app-network \  # Added network
            -p 8080:80 \
            ${{ secrets.DOCKER_USERNAME }}/frontend:latest
        EOF
